name: CI
on:
  workflow_dispatch:
  push: # run on pushes to main (only happens when PRs are merged or admin commits directly to main)
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "Directory.Build.props"
      - "global.json"
      - "src/**"
      - "tests/**"
  pull_request: # run on all PR actions (push, open, reopen)
    paths:
      - ".github/workflows/ci.yml"
      - "Directory.Build.props"
      - "global.json"
      - "src/**"
      - "tests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOTNET_VERSION: 10.0.x

jobs:
  ci:
    name: 🧪 CI
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          filter: tree:0
      - name: ✨ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🛠️ Build
        run: dotnet build "NoticeGenerator.slnx" --configuration Release
      - name: 🧪 Test
        run: dotnet test "NoticeGenerator.slnx" --configuration Release --no-build --verbosity normal
