name: Release

on:
  workflow_dispatch:

env:
  TARGET_PROJECT_NAME: "NoticeGenerator"
  TARGET_PROJECT_PATH: "src/NoticeGenerator/NoticeGenerator.csproj"
  NUGET_SOURCE_NAME: "${{ github.repository_owner }} GitHub Packages"
  NUGET_PACKAGE_ID: "${{ github.repository_owner }}.NoticeGenerator"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: 💡 gh --version
        run: gh --version
      - name: 🛒 Checkout
        uses: actions/checkout@v6.0.2
      - name: ✨ Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: 📝 Update Version
        id: versioning
        run: |
          # タイムゾーン設定 (Linux 環境向けに Asia/Tokyo を使用)
          $JstTimeZone = [TimeZoneInfo]::FindSystemTimeZoneById("Asia/Tokyo")
          $UtcDate = (Get-Date).ToUniversalTime()
          $JstDate = [TimeZoneInfo]::ConvertTimeFromUtc($UtcDate, $JstTimeZone)
          
          # バージョン生成
          $VERSION = $JstDate.ToString("yyyy.M.d.HHmm")
          "version=$VERSION" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          # csproj 更新
          $csprojPath = "${{ env.TARGET_PROJECT_PATH }}"
          [xml]$xml = Get-Content $csprojPath
          $xml.Project.PropertyGroup | ? Version | % { $_.Version = $VERSION }
          $xml.Save($csprojPath)
          
          # Git コミット & プッシュ
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add $csprojPath
          if (-not (git diff --staged --quiet)) {
              git commit -m "Bump version to $VERSION [skip ci]"
              git push
          }
      - name: 🚚 Restore
        run: dotnet restore "${{ env.TARGET_PROJECT_PATH }}"
      - name: 🛠️ Build
        run: dotnet build "${{ env.TARGET_PROJECT_PATH }}" --configuration Release --no-restore
      - name: 🚀 Publish ${{ env.TARGET_PROJECT_NAME }}
        run: dotnet publish "${{ env.TARGET_PROJECT_PATH }}" --configuration Release -p:PublishProfile=FolderProfile --output "./artifacts/${{ env.TARGET_PROJECT_NAME }}"

      - name: 🗜️ Zip artifacts
        run: |
          $zipName = "${{ env.TARGET_PROJECT_NAME }}-win-x64.zip"
          Compress-Archive -Path "./artifacts/${{ env.TARGET_PROJECT_NAME }}/*" -DestinationPath "./artifacts/$zipName"
      - name: 🎨 Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.TARGET_PROJECT_NAME }}-win-x64
          path: ./artifacts/${{ env.TARGET_PROJECT_NAME }}-win-x64.zip
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

      - name: 📦 Pack
        run: dotnet pack "${{ env.TARGET_PROJECT_PATH }}" --configuration Release --output ./nupkg
      - name: 🚢 Publish to GitHub Packages NuGet Registry
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
            --name "${{ env.NUGET_SOURCE_NAME }}" `
            --username "token" `
            --password ${{ secrets.GPR_API_KEY }} `
            --store-password-in-clear-text
          dotnet nuget push "**/*.nupkg" `
            --api-key ${{ secrets.GPR_API_KEY }} `
            --source "${{ env.NUGET_SOURCE_NAME }}" `
            --skip-duplicate

      - name: 🎉 Publish Latest Release
        env:
          TAG_NAME: "v${{ steps.versioning.outputs.version }}"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release create ${{ env.TAG_NAME }} --title "Release ${{ env.TAG_NAME }}" --generate-notes --draft --prerelease

            gh release upload ${{ env.TAG_NAME }} "./artifacts/${{ env.TARGET_PROJECT_NAME }}-win-x64.zip"

            Get-ChildItem "./nupkg" -File | ForEach-Object {
              gh release upload ${{ env.TAG_NAME }} $_.FullName
            }

            gh release edit ${{ env.TAG_NAME }} --draft=false --prerelease=false --latest
      - name: 📣 Release summary
        run: |
          $VERSION = "${{ steps.versioning.outputs.version }}"
          $ARTIFACT_NAME = "${{ env.TARGET_PROJECT_NAME }}-win-x64"
          $PACKAGE_ID = "${{ env.NUGET_PACKAGE_ID }}"
          $RUN_URL = "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          @"
          ### ✅ Succeeded! 🌟

          | 項目 | 値 |
          | --- | --- |
          | 📦 Package | ``${PACKAGE_ID}`` |
          | 🏷️ Version | ``${VERSION}`` |
          | 🗂️ Artifact | [``${ARTIFACT_NAME}``](${RUN_URL}) |

          #### dotnet tool install
          ``````ps1
          dotnet tool install ${PACKAGE_ID} --version ${VERSION}
          ``````
          "@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
